project:
  type: website
  output-dir: docs

website:
  title: "psci3200-lukegooding-finalproject"
  navbar:
    left:
      - href: index.qmd
        text: Project
      - href: about.qmd
        text: Appendix
        
bibliography: bib.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

