---
title: "Appendix"
---

## Appendix

### Assignment Algorithm

-   The number of school slots at each school is predetermined based on capacity constraints.
-   Students are tentatively placed in the applicant pools for their first-choice schools and are ranked in descending order by SEA score within each application pool.
-   The school at which the n~j~th ranked applicant has the highest SEA score is determined to be the most highly subscribed/ranked school, this score becomes the cutoff score for this school, and the top n~j1~ students in the applicant pool for top-ranked school j1 are admitted to school j2.
-   The top-ranked school's slots and the admitted students are removed from the process, and the second choice becomes the new first choice for students who had the top-ranked school as their first choice but did not gain admission.
-   The process repeats in another round to assign students to the second highest ranked school j2 and determine the cutoff score for the second-ranked school.
-   The process repeats in subsequent rounds until all slots are filled.